{{- if not (lookup "v1" "ServiceAccount" .Release.Namespace "tailwinds-sa")}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tailwinds-dns-diagnostic-server.serviceAccountName" . }}
  labels:
    {{- include "tailwinds-dns-diagnostic-server.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
