{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: {{ include "tailwinds-security-image-scanner.fullname" . }}
rules:
  - apiGroups: [""]
    resources:
    - configmaps
    - deployments
    - endpoints
    - horizontalpodautoscalers
    - namespaces
    - nodes
    - persistentvolumes
    - persistentvolumeclaims
    - pods
    - secrets
    - serviceaccounts
    - services
    - statefulsets
    verbs: ["get", "watch", "list"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
    - clusterroles
    - clusterrolebindings
    - roles
    - rolebindings
    verbs: ["get", "watch", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources:
    - pods
    - nodes
    verbs: ["get", "watch", "list"]
{{- end }}
