{
 "title": "Detailed pods resources",
 "description": "Get your Kubernetes pods resources usage by namespaces ",
 "tags": [
  "kubernetes",
  "namespaces",
  "pods"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels,namespace)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"},container)"
    }
   },
   {
    "name": "podname",
    "label": "Pod Name",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\",container=\"$container\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace Global Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "content": "\n## CPU Usage\n\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "CPUs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"$container\"}[$__range]))",
     "legendFormat": "${namespace} CPU Usage (Nb of CPUs)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "options": { "content": "\n## Memory Usage\n\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container_name=\"$container\"})",
     "legendFormat": "${namespace} Memory Usage"
    },
    {
     "expr": "sum(container_memory_cache{namespace=\"$namespace\",container=\"$container\"})",
     "legendFormat": "${namespace} Cache Usage"
    }
   ]
  },
  {
   "type": "gauge",
   "description": "Percent of limits CPU usage ",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"$container\"}[$__range])) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\",container=\"$container\", resource=\"cpu\"}) * 100",
     "legendFormat": "Limits CPU Usage"
    },
    { "legendFormat": "Limits" }
   ]
  },
  {
   "type": "gauge",
   "description": "Percent of limits memory usage",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container=\"$container\"}) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\",container=\"$container\", resource=\"memory\"}) * 100",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"$container\"}[$__range]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container=\"$container\"})"
    }
   ]
  },
  {
   "title": "Network I/O /5min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=\"${namespace}\"}[5m]))",
     "legendFormat": "Bytes recieves"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{namespace=\"${namespace}\"}[5m]))",
     "legendFormat": "Bytes sents"
    }
   ]
  },
  {
   "title": "Network Nb of Errors /5min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_errors_total{namespace=\"${namespace}\"}[5m]))",
     "legendFormat": "Errors recives"
    },
    {
     "expr": "sum (rate (container_network_transmit_errors_total{namespace=\"${namespace}\"}[5m]))",
     "legendFormat": "Errors Sents"
    }
   ]
  },
  {
   "title": "Network Nb of Packets /(5mins)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_packets_total{namespace=\"${namespace}\"}[5m]))",
     "legendFormat": "Bytes recieves"
    },
    {
     "expr": "- sum (rate (container_network_transmit_packets_total{namespace=\"${namespace}\"}[5m]))",
     "legendFormat": "Bytes sents"
    }
   ]
  },
  {
   "title": "$namespace - $container resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "container",
   "targets": [
    {}
   ]
  },
  {
   "title": "${podname} - cpu usage, requests and limits",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 20 },
   "repeat": "podname",
   "yaxes": [
    { "format": "short", "label": "CPU" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"$container\"}[$__range])",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"$namespace\",container=\"$container\",resource=\"cpu\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\",container=\"$container\",resource=\"cpu\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "$podname - memory requests and limits",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 20 },
   "repeat": "podname",
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\",container=\"$container\"}",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"$namespace\",container=\"$container\",resource=\"memory\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\",container=\"$container\",resource=\"memory\"})",
     "legendFormat": "Request"
    }
   ]
  }
 ]
}