apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "tailwinds-security-kubernetes-scanner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tailwinds-security-kubernetes-scanner.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tailwinds-security-kubernetes-scanner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tailwinds-security-kubernetes-scanner.selectorLabels" . | nindent 8 }}
    spec:
      hostPID: true
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # command: [ "/bin/sh", "-c", "--" ]
          # args: ["while true; do echo \"***START SCAN REPORT***\"; eval kube-bench \"$@\"; echo \"***END SCAN REPORT***\"; sleep 3h; done;"]
          volumeMounts:
           - name: var-lib-etcd
             mountPath: /var/lib/etcd
             readOnly: true
           - name: var-lib-kubelet
             mountPath: /var/lib/kubelet
             readOnly: true
           - name: etc-systemd
             mountPath: /etc/systemd
             readOnly: true
           - name: etc-kubernetes
             mountPath: /etc/kubernetes
             readOnly: true
              # /usr/local/mount-from-host/bin is mounted to access kubectl / kubelet, for auto-detecting the Kubernetes version.
              # You can omit this mount if you specify --version as part of the command.
           - name: usr-bin
             mountPath: /usr/local/mount-from-host/bin
             readOnly: true
      restartPolicy: Always

      volumes:
        - name: var-lib-etcd
          hostPath:
            path: "/var/lib/etcd"
        - name: var-lib-kubelet
          hostPath:
            path: "/var/lib/kubelet"
        - name: etc-systemd
          hostPath:
            path: "/etc/systemd"
        - name: etc-kubernetes
          hostPath:
            path: "/etc/kubernetes"
        - name: usr-bin
          hostPath:
            path: "/usr/bin"





