{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
   name: {{ include "tailwinds-visibility-scanner.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "tailwinds-visibility-scanner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "tailwinds-visibility-scanner.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}

