apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tailwinds-visibility-scanner.fullname" . }}
  labels:
    {{- include "tailwinds-visibility-scanner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tailwinds-visibility-scanner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tailwinds-visibility-scanner.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tailwinds-visibility-scanner.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: [ "/bin/sh", "-c", "--"]
          args: ["while true; do echo \"***START SCAN REPORT***\"; eval /bin/popeye -o json; echo \"***END SCAN REPORT***\"; sleep 2m; done;"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
               cpu: 500m
               memory: 100Mi

